import {
  Heart,
  DollarSign,
  Home,
  TrendingUp,
  Briefcase,
  Coffee,
  Sparkles,
  Award,
  BookOpen,
  Calendar,
  CheckCircle,
  Clock,
  Code2,
  CreditCard,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Layout,
  Monitor,
  Music,
  Phone,
  Plane,
  Server,
  Settings,
  Shield,
  Smartphone,
  Smile,
  Star,
  Sun,
  Target,
  TreeDeciduous,
  Trophy,
  Users,
  Video,
  Wallet,
  Zap,
  Activity,
  Stethoscope,
  Pill,
  Bandage,
  PiggyBank,
  Receipt,
  Building,
  Dumbbell,
  Sunset,
  Rocket,
  ChartLine,
  Medal,
  LucideIcon,
} from "lucide-react";
import { createElement, type ComponentType } from "react";

export const ICON_MAP: Record<string, LucideIcon> = {
  heart: Heart,
  "dollar-sign": DollarSign,
  home: Home,
  "trending-up": TrendingUp,
  briefcase: Briefcase,
  coffee: Coffee,
  sparkles: Sparkles,
  award: Award,
  book: BookOpen,
  calendar: Calendar,
  "check-circle": CheckCircle,
  clock: Clock,
  code: Code2,
  "credit-card": CreditCard,
  gift: Gift,
  globe: Globe,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  layout: Layout,
  monitor: Monitor,
  music: Music,
  phone: Phone,
  plane: Plane,
  server: Server,
  settings: Settings,
  shield: Shield,
  smartphone: Smartphone,
  smile: Smile,
  star: Star,
  sun: Sun,
  target: Target,
  tree: TreeDeciduous,
  trophy: Trophy,
  users: Users,
  video: Video,
  wallet: Wallet,
  zap: Zap,
  activity: Activity,
  stethoscope: Stethoscope,
  pill: Pill,
  bandage: Bandage,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  building: Building,
  dumbbell: Dumbbell,
  sunset: Sunset,
  rocket: Rocket,
  "chart-line": ChartLine,
  medal: Medal,
};

export function DynamicIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICON_MAP[name];
  if (!Icon) return null;
  return createElement(Icon as ComponentType<any>, { className });
}
