export { LandingHeader } from "./header"
export { Footer } from "../footer"
export { Hero } from "./hero"
export { default as CXHeroSearch } from "./cx-hero-search"
export { TrustedStrip } from "./trusted-strip"
export { CategoriesSection } from "./categories-section"
export { FeaturedSection } from "./featured-section"
export { BenefitsSection } from "./benefits-section"
export { default as RecruiterCTA } from "./recruiter-cta"
